# fly.toml app configuration file generated for fastapi-9hnr6q on 2025-08-12T22:39:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastapi-9hnr6q'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
